In [1]:
import numpy as np
import pandas as pd
import random
import tensorflow as tf

from tensorflow import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Bidirectional
from keras.layers import LSTM, RepeatVector, TimeDistributed
from sklearn.model_selection import train_test_split
from keras import optimizers
from keras.models import load_model

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import string

Using TensorFlow backend.


In [2]:
names =  pd.read_csv('sheet_1.csv', error_bad_lines = False, encoding='latin-1')

In [3]:
names.head()

response_id        class                                      response_text  \
0  response_1  not_flagged              I try and avoid this sort of conflict   
1  response_2      flagged  Had a friend open up to me about his mental ad...   
2  response_3      flagged  I saved a girl from suicide once. She was goin...   
3  response_4  not_flagged  i cant think of one really...i think i may hav...   
4  response_5  not_flagged  Only really one friend who doesn't fit into th...   

  Unnamed: 3  Unnamed: 4 Unnamed: 5  Unnamed: 6 Unnamed: 7  
0        NaN         NaN        NaN         NaN        NaN  
1        NaN         NaN        NaN         NaN        NaN  
2        NaN         NaN        NaN         NaN        NaN  
3        NaN         NaN        NaN         NaN        NaN  
4                    NaN        NaN         NaN        NaN

In [4]:
names = names.drop(['response_id','class','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7'], axis=1)

In [5]:
len(names)

80

In [6]:
data = []
for i in range(len(names)):
    x = names.iloc[i][0].split()
    if len(x) > 8:
        x = x[:8]
    elif len(x) < 8:
        while(len(x) != 8):
            x.append('9')
    for k in range(8):
        x[k] = x[k].translate(str.maketrans('', '', string.punctuation))
    data.append(x)

In [7]:
vocab = set(x for l in data for x in l)

In [8]:
len(vocab)

282

In [9]:
vocabulary = list(vocab)
vocabulary = np.array(vocabulary)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(vocabulary)

In [10]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


C:\Users\Vee\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [11]:
model = load_model('LSTM_generator1.h5')

C:\Users\Vee\Anaconda3\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [18]:
for i in range(3):
    faux = np.random.normal(0,1,(10,10))
    faux = faux.reshape(1,10,10)
    jamie = model.predict_on_batch(faux)
    for y in range(8):
        inverted = label_encoder.inverse_transform([argmax(jamie[0][y])])
        if(inverted == '9'):
            break
        print(inverted[0], end =" ")
    print('\n')

friend friend friend friend friend friend friend friend 

friend friend friend friend friend friend friend friend 

friend friend friend friend friend friend friend friend 

